load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Google test
http_archive(
    name = "com_google_googletest",
    strip_prefix = "googletest-7a7231c442484be389fdf01594310349ca0e42a8",
    urls = ["https://github.com/google/googletest/archive/7a7231c442484be389fdf01594310349ca0e42a8.zip"],
)

# Boost
# Famous C++ library that has given rise to many new additions to the C++ Standard Library
# Makes @boost available for use: For example, add `@boost//:algorithm` to your deps.
# For more, see https://github.com/nelhage/rules_boost and https://www.boost.org
http_archive(
    name = "com_github_nelhage_rules_boost",
    strip_prefix = "rules_boost-27c9ef79a5455036086c1679889f14732e603f41",

    # Replace the commit hash in both places (below) with the latest, rather than using the stale one here.
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
    url = "https://github.com/nelhage/rules_boost/archive/27c9ef79a5455036086c1679889f14732e603f41.tar.gz",
    # When you first run this tool, it'll recommend a sha256 hash to put here with a message like: "DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = ..."
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")

boost_deps()
